// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutArtist: typeof import('./src/pages/artistDetail/components/AboutArtist.vue')['default']
    Artist: typeof import('./src/pages/home/components/Artist.vue')['default']
    ArtistDetail: typeof import('./src/pages/artistDetail/index.vue')['default']
    Artwork: typeof import('./src/pages/home/components/Artwork.vue')['default']
    Banner: typeof import('./src/pages/home/components/banner/Banner.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/pages/home/components/banner/Card.vue')['default']
    Catena: typeof import('./src/pages/catena/index.vue')['default']
    CatenaDetail: typeof import('./src/pages/catena/components/CatenaDetail.vue')['default']
    CatenaSidebar: typeof import('./src/pages/catena/components/CatenaSidebar.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Detail: typeof import('./src/pages/catena/components/Detail.vue')['default']
    Explore: typeof import('./src/pages/explore/index.vue')['default']
    Footer: typeof import('./src/layouts/components/Footer.vue')['default']
    Header: typeof import('./src/layouts/components/Header.vue')['default']
    Home: typeof import('./src/pages/home/index.vue')['default']
    JoinUs: typeof import('./src/pages/home/components/JoinUs.vue')['default']
    Masonry: typeof import('./src/components/Masonry.vue')['default']
    Ranking: typeof import('./src/pages/home/components/Ranking.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/pages/catena/components/CatenaSidebar.vue')['default']
    Undefined: typeof import('./src/layouts/index.vue')['default']
    Works: typeof import('./src/pages/artistDetail/components/Works.vue')['default']
  }
}
