<template>
  <button
    class="
      group
      relative
      overflow-hidden
      border-2 border-black
      px-12
      py-2
      font-bold
      text-black
      transition
      duration-700
      hover:bg-primary hover:text-white
    "
  >
    MORE
    <span
      class="
        absolute
        -right-2
        -bottom-6
        h-full
        w-[25px]
        rotate-45
        bg-primary
        transition
        duration-700
        group-hover:bg-black
      "
    />
  </button>
</template>
